# Generated by Django 5.2.7 on 2025-11-10 05:34

import django.db.models.deletion
import django.utils.timezone
import lottery_app.utils.encrypt_decrypt_data
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prize',
            name='location',
        ),
        migrations.RemoveField(
            model_name='prize',
            name='ticket_number',
        ),
        migrations.AlterField(
            model_name='lottery',
            name='created_at',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedDateTimeField(),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotteries', to='lottery_app.userprofile'),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='lottery_name',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='status',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('upcoming', 'Upcoming')], max_length=20),
        ),
        migrations.AlterField(
            model_name='prize',
            name='created_at',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedDateTimeField(),
        ),
        migrations.AlterField(
            model_name='prize',
            name='prize_amount',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedDecimalField(blank=True, decimal_places=2, help_text='Amount of the prize', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='prize',
            name='prize_name',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(blank=True, help_text="e.g.,'1st Prize', '2nd Prize'", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedDateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(choices=[('SuperAdmin', 'SuperAdmin'), ('Admin', 'Admin'), ('User', 'User')], default='User', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(help_text='Ad title', max_length=100)),
                ('image', models.ImageField(help_text='Ad image', upload_to='ads/')),
                ('redirect_url', lottery_app.utils.encrypt_decrypt_data.EncryptedURLField(blank=True, help_text='Optional link when ad is clicked', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the ad is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when created')),
                ('created_by', models.ForeignKey(help_text='Admin who uploaded this advertisement', limit_choices_to={'user__role': 'Admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='lottery_app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(help_text='Notification title', max_length=100)),
                ('message', lottery_app.utils.encrypt_decrypt_data.EncryptedTextField(help_text='Notification message content')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read')),
                ('created_at', lottery_app.utils.encrypt_decrypt_data.EncryptedDateTimeField(help_text='Timestamp when notification was created')),
                ('user', models.ForeignKey(blank=True, help_text='Target user (null = broadcast to all)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='lottery_app.userprofile')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(max_length=6)),
                ('created_at', lottery_app.utils.encrypt_decrypt_data.EncryptedDateTimeField()),
                ('expires_at', lottery_app.utils.encrypt_decrypt_data.EncryptedDateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(choices=[('Plan 1', 'Plan 1'), ('Plan 2', 'Plan 2'), ('Plan 3', 'Plan 3')], help_text='Prediction plan type', max_length=20)),
                ('predicted_numbers', models.JSONField(help_text='List of numbers predicted')),
                ('prediction_date', lottery_app.utils.encrypt_decrypt_data.EncryptedDateTimeField()),
                ('accuracy_score', models.FloatField(default=0, help_text='Accuracy from ML model (if available)')),
                ('lottery', models.ForeignKey(help_text='Related lottery', on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='lottery_app.lottery')),
                ('prize', models.ForeignKey(help_text='Related prize', on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='lottery_app.prize')),
                ('user', models.ForeignKey(help_text='Who made the prediction', on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='lottery_app.userprofile')),
            ],
            options={
                'verbose_name': 'Prediction',
                'verbose_name_plural': 'Predictions',
                'ordering': ['-prediction_date'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lottery_name', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(blank=True, help_text='Name of the lottery', max_length=100, null=True)),
                ('winning_number', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(help_text='Winning number for this prize', max_length=50)),
                ('prizes', models.JSONField(blank=True, default=dict, help_text='Additional prize details in JSON format', null=True)),
                ('location', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(blank=True, help_text="e.g., 'Thiruvananthapuram'", max_length=100, null=True)),
                ('result_date', lottery_app.utils.encrypt_decrypt_data.EncryptedDateField(default=django.utils.timezone.now, help_text='Date and time the result was announced')),
                ('created_at', lottery_app.utils.encrypt_decrypt_data.EncryptedDateTimeField()),
                ('lottery', models.ForeignKey(blank=True, help_text='Related lottery', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='lottery_app.lottery')),
                ('prize', models.ForeignKey(blank=True, help_text='Related prize', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='lottery_app.prize')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='Admin who uploaded this result', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_results', to='lottery_app.userprofile')),
            ],
            options={
                'verbose_name': 'Lottery Result',
                'verbose_name_plural': 'Lottery Results',
                'ordering': ['-result_date'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(choices=[('Basic', 'Basic'), ('Premium', 'Premium'), ('Elite', 'Elite')], help_text='e.g., "Basic", "Premium", "Elite"', max_length=50)),
                ('price', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(help_text='Subscription price', max_length=50)),
                ('start_date', lottery_app.utils.encrypt_decrypt_data.EncryptedDateField(help_text='Subscription start date')),
                ('end_date', lottery_app.utils.encrypt_decrypt_data.EncryptedDateField(help_text='Subscription end date')),
                ('is_active', models.BooleanField(default=True, help_text='Subscription active or not')),
                ('created_at', lottery_app.utils.encrypt_decrypt_data.EncryptedDateTimeField(help_text='Created timestamp')),
                ('user', models.ForeignKey(help_text='Subscribed user', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='lottery_app.userprofile')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', lottery_app.utils.encrypt_decrypt_data.EncryptedDecimalField(decimal_places=2, help_text='Paid amount', max_digits=10)),
                ('payment_method', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(choices=[('UPI', 'UPI'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Net Banking', 'Net Banking')], help_text='Payment method type', max_length=50)),
                ('transaction_id', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(help_text='Unique transaction reference', max_length=100, unique=True)),
                ('payment_status', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed')], default='Pending', help_text='Payment status', max_length=20)),
                ('created_at', lottery_app.utils.encrypt_decrypt_data.EncryptedDateTimeField(help_text='Payment time')),
                ('user', models.ForeignKey(help_text='Paying user', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='lottery_app.userprofile')),
                ('subscription', models.ForeignKey(help_text='Linked subscription', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='lottery_app.subscription')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
