# Generated by Django 5.2.7 on 2025-11-10 05:45

import lottery_app.utils.encrypt_decrypt_data
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_app', '0003_alter_lottery_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(help_text='Ad title', max_length=500),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='lottery_name',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='status',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('upcoming', 'Upcoming')], max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(help_text='Notification title', max_length=700),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='otp',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(choices=[('UPI', 'UPI'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Net Banking', 'Net Banking')], help_text='Payment method type', max_length=500),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed')], default='Pending', help_text='Payment status', max_length=200),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(help_text='Unique transaction reference', max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='plan_type',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(choices=[('Plan 1', 'Plan 1'), ('Plan 2', 'Plan 2'), ('Plan 3', 'Plan 3')], help_text='Prediction plan type', max_length=400),
        ),
        migrations.AlterField(
            model_name='prize',
            name='prize_name',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(blank=True, help_text="e.g.,'1st Prize', '2nd Prize'", max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='location',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(blank=True, help_text="e.g., 'Thiruvananthapuram'", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='lottery_name',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(blank=True, help_text='Name of the lottery', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='winning_number',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(help_text='Winning number for this prize', max_length=200),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan_name',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(choices=[('Basic', 'Basic'), ('Premium', 'Premium'), ('Elite', 'Elite')], help_text='e.g., "Basic", "Premium", "Elite"', max_length=500),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(help_text='Subscription price', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(choices=[('SuperAdmin', 'SuperAdmin'), ('Admin', 'Admin'), ('User', 'User')], default='User', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(max_length=400),
        ),
    ]
