# Generated by Django 5.2.7 on 2025-11-10 06:25

import lottery_app.utils.encrypt_decrypt_data
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_app', '0004_alter_advertisement_title_alter_lottery_lottery_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('pro', 'Pro')], default='basic', max_length=300)),
                ('title', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(default='Basic', max_length=500)),
                ('description', lottery_app.utils.encrypt_decrypt_data.EncryptedTextField(default='Get started with basic predictions')),
                ('price', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(default='99.00', max_length=400)),
                ('duration_in_months', models.PositiveIntegerField(default=1)),
                ('predictions_per_month', models.PositiveIntegerField(default=10)),
                ('prizes_included', lottery_app.utils.encrypt_decrypt_data.EncryptedTextField(default='7th, 8th & 9th Prizes Only', max_length=255)),
                ('numbers_per_prediction', models.PositiveIntegerField(default=15)),
                ('show_prediction_percentage', models.BooleanField(default=True)),
                ('low_risk_prediction', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
