# Generated by Django 5.2.7 on 2025-11-11 06:02

import lottery_app.utils.encrypt_decrypt_data
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_app', '0005_subscriptionplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedEmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
