# Generated by Django 5.2.7 on 2025-11-11 06:15

import lottery_app.utils.encrypt_decrypt_data
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_app', '0006_alter_user_email_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(choices=[('SuperAdmin', 'SuperAdmin'), ('Admin', 'Admin'), ('User', 'User')], default='User', max_length=600),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(max_length=600),
        ),
    ]
