# Generated by Django 5.2.7 on 2025-11-11 06:18

import lottery_app.utils.encrypt_decrypt_data
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_app', '0007_alter_user_full_name_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedImageField(blank=True, max_length=700, null=True, upload_to='profile_pictures/'),
        ),
    ]
