# Generated by Django 5.2.7 on 2025-11-13 08:31

import lottery_app.utils.encrypt_decrypt_data
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_app', '0008_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='blood_group',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='district',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_field',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_title',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nationality',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nominee_name',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nominee_other_details',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nominee_phone_number',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pincode',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SuperAdmin', 'SuperAdmin'), ('Admin', 'Admin'), ('User', 'User'), ('Dealer', 'Dealer')], default='User', max_length=600),
        ),
    ]
