# Generated by Django 5.2.7 on 2025-11-13 09:51

import lottery_app.utils.encrypt_decrypt_data
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_app', '0009_userprofile_address_userprofile_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pincode',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
    ]
