# Generated by Django 5.2.7 on 2025-11-13 10:42

import django.db.models.deletion
import lottery_app.utils.encrypt_decrypt_data
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_app', '0010_alter_userprofile_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='users_lucky_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(help_text='The lucky number', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the lucky number was created')),
                ('user', models.ForeignKey(help_text='User associated with this lucky number', on_delete=django.db.models.deletion.CASCADE, related_name='lucky_numbers', to='lottery_app.userprofile')),
            ],
            options={
                'verbose_name': 'Lucky Number',
                'verbose_name_plural': 'Lucky Numbers',
                'ordering': ['-created_at'],
            },
        ),
    ]
