# Generated by Django 5.2.7 on 2025-11-13 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_app', '0011_users_lucky_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users_lucky_number',
            new_name='UsersLuckyNumber',
        ),
    ]
