# Generated by Django 5.2.7 on 2025-11-18 07:13

import lottery_app.utils.encrypt_decrypt_data
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_app', '0012_rename_users_lucky_number_usersluckynumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottery',
            name='ticket_rupees',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
    ]
