# Generated by Django 5.2.7 on 2025-11-18 09:30

import lottery_app.utils.encrypt_decrypt_data
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_app', '0013_lottery_ticket_rupees'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottery',
            name='ticket_number',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
    ]
