# Generated by Django 5.2.7 on 2025-12-05 09:25

import lottery_app.utils.encrypt_decrypt_data
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_app', '0015_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceClaimRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(help_text='Rule title', max_length=500)),
                ('description', lottery_app.utils.encrypt_decrypt_data.EncryptedTextField(help_text='Detailed description of the rule')),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
