# Generated by Django 5.2.7 on 2025-12-05 10:41

import lottery_app.utils.encrypt_decrypt_data
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_app', '0016_priceclaimrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsRequiredForPrizeClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(help_text='Name of the required document', max_length=500)),
                ('description', lottery_app.utils.encrypt_decrypt_data.EncryptedTextField(blank=True, help_text='Description or details about the document', null=True)),
                ('is_mandatory', models.BooleanField(default=True, help_text='Whether this document is mandatory for prize claim')),
            ],
        ),
    ]
