# Generated by Django 5.2.7 on 2025-12-09 05:28

import lottery_app.utils.encrypt_decrypt_data
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_app', '0017_documentsrequiredforprizeclaim'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpAndSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(help_text='Help topic title', max_length=500)),
                ('content', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(help_text='Frequently asked question', max_length=700)),
                ('answer', lottery_app.utils.encrypt_decrypt_data.EncryptedTextField(help_text='Answer to the question')),
            ],
        ),
        migrations.CreateModel(
            name='ImportentReminders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', lottery_app.utils.encrypt_decrypt_data.EncryptedTextField(help_text='Reminder message content')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the reminder was created')),
            ],
        ),
    ]
