# Generated by Django 5.2.7 on 2025-12-09 08:23

import lottery_app.utils.encrypt_decrypt_data
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_app', '0018_helpandsupport_importentreminders'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(help_text='Privacy Policy title', max_length=500)),
                ('content', lottery_app.utils.encrypt_decrypt_data.EncryptedTextField(help_text='Privacy policy content')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when last updated')),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(help_text='Terms and Conditions title', max_length=500)),
                ('content', lottery_app.utils.encrypt_decrypt_data.EncryptedTextField(help_text='Terms and conditions content')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when last updated')),
            ],
        ),
    ]
