# Generated by Django 5.2.7 on 2025-12-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_app', '0019_privacypolicy_termsandconditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicy',
            name='created_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when created'),
        ),
        migrations.AddField(
            model_name='termsandconditions',
            name='created_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when created'),
        ),
    ]
