# Generated by Django 5.2.7 on 2025-12-09 10:04

import django.db.models.deletion
import lottery_app.utils.encrypt_decrypt_data
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_app', '0020_privacypolicy_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(max_length=600)),
                ('owner_name', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(max_length=600)),
                ('contact_number', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(max_length=15)),
                ('address', lottery_app.utils.encrypt_decrypt_data.EncryptedTextField(blank=True, null=True)),
                ('city', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(blank=True, max_length=300, null=True)),
                ('email', lottery_app.utils.encrypt_decrypt_data.EncryptedEmailField(blank=True, max_length=254, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('license_expiry_date', models.DateField(blank=True, null=True)),
                ('id_documents', models.FileField(blank=True, max_length=700, null=True, upload_to='dealer_id_documents/')),
                ('state', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(blank=True, max_length=300, null=True)),
                ('pincode', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(blank=True, max_length=300, null=True)),
                ('profile_picture', models.ImageField(blank=True, max_length=700, null=True, upload_to='dealer_profile_pictures/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
