# Generated by Django 5.2.7 on 2025-12-09 11:01

import lottery_app.utils.encrypt_decrypt_data
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_app', '0021_dealerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerprofile',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='registration_number',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(blank=True, max_length=400, null=True),
        ),
    ]
