# Generated by Django 5.2.7 on 2025-12-09 11:16

import lottery_app.utils.encrypt_decrypt_data
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_app', '0022_dealerprofile_registration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerprofile',
            name='contact_number',
            field=lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(max_length=200),
        ),
    ]
