# Generated by Django 5.2.7 on 2025-12-11 04:38

import lottery_app.utils.encrypt_decrypt_data
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_app', '0023_alter_dealerprofile_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('established', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(max_length=200)),
                ('draw_time', models.TimeField()),
                ('draw_location', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(max_length=255)),
                ('ticket_price', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(max_length=100)),
                ('age_requirement', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(max_length=100)),
                ('claim_period', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='accountsupporthelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(max_length=1300)),
                ('description', lottery_app.utils.encrypt_decrypt_data.EncryptedTextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_email', models.EmailField(max_length=254)),
                ('support_hours', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(max_length=1200)),
                ('closed_info', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField()),
            ],
        ),
        migrations.CreateModel(
            name='GeneralHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(max_length=1300)),
                ('description', lottery_app.utils.encrypt_decrypt_data.EncryptedTextField()),
            ],
        ),
        migrations.CreateModel(
            name='ImportantRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(max_length=555)),
            ],
        ),
        migrations.CreateModel(
            name='LotteryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(max_length=200)),
                ('description', lottery_app.utils.encrypt_decrypt_data.EncryptedTextField()),
            ],
        ),
        migrations.CreateModel(
            name='OfficialResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(max_length=1500)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='paymentandsubscriptionhelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(max_length=1300)),
                ('description', lottery_app.utils.encrypt_decrypt_data.EncryptedTextField()),
            ],
        ),
        migrations.CreateModel(
            name='purchaselotteryhelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(max_length=1300)),
                ('description', lottery_app.utils.encrypt_decrypt_data.EncryptedTextField()),
            ],
        ),
        migrations.CreateModel(
            name='SafetyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(max_length=655)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(max_length=600)),
                ('lottery_name', lottery_app.utils.encrypt_decrypt_data.EncryptedCharField(max_length=700)),
                ('draw_time', models.TimeField()),
            ],
        ),
    ]
